- src/lib.rs
Adds newline before list of ScopedPool differences so rustdoc will render a list and not append it to the previous paragraph.
You can currently see the problem in the second paragraph on http://doc.rust-lang.org/threadpool/threadpool/struct.ScopedPool.html
> Fix Minor Markdown Syntax Problem In Comment

- src/lib.rs
Just noted on the documentation, a quick fix for this renaming follow-up
> Rename TaskPool -> ThreadPool in doc/comment

- src/lib.rs
Current version in crates.io failed to build with most recent nightly due to rust-lang/rust#23752.
> Fix for failed build with latest nightly

- Cargo.toml
- src/lib.rs
`thread::Scoped` has been marked unstable due to a memory safety hole.
r? @alexcrichton
> Hide `ScopedPool` behind a cargo feature

- src/lib.rs
The type of "threads" was updated to be a usize for
consistency with ThreadPool::new.
> update ScopedPool::new arguments

- src/lib.rs
We don't use `rust` in API documentation.
> Update formatting to conventions

- src/lib.rs
A ThreadPool is really a handle to a thread pool.
This patch makes it possible to clone the ThreadPool object
and use it from multiple threads to start more threads.
> Make ThreadPool cloneable

- Cargo.toml
Bumped to 0.2.0 instead of 0.1.5 because the `scoped-pool` feature was
removed, which could break code.
> Bump version: 0.1.4 -> 0.2.0

- Cargo.toml
- src/lib.rs
This PR builds on PR #15, adding not only the ```max_count``` and ```active_count``` functions but also the ```set_threads``` function to change the thread number at runtime, and is, at the time of writing, fully up to date with the current repo. Essentially, the ```set_threads``` function changes the maximum thread number, and if the new thread number is more than the current one, the ```set_threads``` function spawns threads to compensate. If the new thread number is less than the current one, existing threads will end after they finish their current job (they won't be killed). A lot of variable names are kind of iffy, so any input would be appreciated.
> Add set_threads function to set thread number at runtime

- src/lib.rs
This should speed up the active_count of the pool gets polled many times from monitoring threads.
> Switch active_count from Mutex to RwLock for more performance

- src/lib.rs
I tried making the pool faster on NUMA systems but the effect is very minor, because the channel uses a Mutex.
However, since I already did the work, I would like to share it.
Should I rebase the history into one commit?
> Use atomic counters

- src/lib.rs
An attempt to differentiate/clarify the parameter name.
> Rename `threads` param to `num_threads`.

- README.md
- src/lib.rs
I wrote an example with a barrier.
> Barrier sync example

- src/lib.rs
No need to make the user manually count to find out what's happening, so we'll simplify the math.
> Simplify math in example.

- src/lib.rs
rustfmt doesn't like when lines are longer than a certain number of
characters, and this line was 111 characters.
> Wrap wrong line so rustfmt works again.

- .travis.yml
- CHANGES.md
- README.md
- lib.rs
> Enable `#[deprecated]` doc, requires rust 1.9

- lib.rs
Type T which implement FnOnce() should be directly moved into a box.
> Remove redundant closure

- lib.rs
> Use fmt::Formatter::debug_struct to implement fmt::Debug

- CHANGES.md
- lib.rs
it restricts the operation to observer only.
Because the `std::sync::mpsc::channel` does not offer a way to query the queue length I added another counter field: stored_jobs_counter
> Implementation of the join operation

- lib.rs
I fixed some typos I found in the docs while preparing a talk.
Also I am wondering if we should update the examples on crate-level.
Maybe add an example with join or explain why the channel example requires the `take(n)` after the `iter()`.
> Fixing typos

- lib.rs
The tests are run at compile time. Found the trick at [the api-guidlines](https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#types-are-send-and-sync-where-possible-c-send-sync).
> Add test to make sure the types in the pool stay Send and/or Sync

- Cargo.toml
- lib.rs
The example became rather long but it is the shortest one I could come up with with one pool.
I am open to suggestions.
> Document `.clone()`

- src/lib.rs
I considered linking the `take()` in the 'Examples' section of the
module-level docs to the std library's `Iter::take()`. However, I think
this would be unncessary noise: the reference to `take()` is only there
to point to a specific point in the example code below it.
What do you think?
Fixes #85.
> Add more hyperlinks to documentation.

- Cargo.toml
- Add a set of keywords that I'd search for when looking for a similar
library.
- Add the 'os' category - there seem to be other libraries in that
category that offer similar abstractions on top of OS level features
like threads.
- Considered (but didn't) add the 'asynchronous' category. The
crates.io description for that category suggest it's exclusively for
Tokio-like libraries.
Fixes #84.
> Add keywords and categories to Cargo.toml.

- src/lib.rs
Related to https://github.com/rust-threadpool/rust-threadpool/issues/77.
> Initial implementation of `threadpool::Builder`.

- .gitignore
- src/lib.rs
When I talked about the threadpool at the Zürichsee meetup somebody came up with a problem when multiple threads join on a pool.
The scenario is joining threads should not be stuck once their wave
of joins has completed. So once one thread joining on a pool has
succeded other threads joining on the same pool must get out even if
the thread is used for other jobs while the first group is finishing
their join
> Join waves

- src/lib.rs
The existing link is to the older references pages and redirected users to the TOC for the latest reference pages. This change updates the path to the current url.
> Update link to not-unsafe behavior reference

- .travis.yml
- CHANGES.md
- Cargo.toml
- README.md
- appveyor.yml
- src/lib.rs
Hi All
I added some documentation:
* Explicit magic constant
* Remove the last warning while running the tests
* Document the development with rustup
Best,
Stefan
> Improved Docs and raise minimal rustc version to 1.13.0

- src/lib.rs
Fixed a typo in doc that caused the link to display improperly.
> fix a typo
